version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: validqr-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: validqr

  redis:
    image: redis:7-alpine
    container_name: validqr-redis
    ports:
      - "6379:6379"